### ISSUE TITLE
Commandline doesn't respect sectionsep parameter as expected 

### ISSUE THREAD

**Issue by dginzbourg** [staffanm/layeredconfig#13]
Hi
First of all - I really like this project, it saved a lot of time and made working with configuration in dockers much easier, many thanks to you.
I tried to use command line parser, to pass parameter like log.rotation_size=100 with sectionsep='.', but it splits everything by '_'. I checked the code and '_' is just hardcoded. The same parameter naming convention works fine in Environment. I replaced '_' with self.sectoinsep in commandline.py and it works great. Any particular reason why you put '_' hardcoded in Commandline? If not, can it be fixed? thanks

**Comment by staffanm** [comment]
This has been fixed in the just-released 0.3.3 version. Sorry about the long delay!
